In [ ]:
import pandas as pd
df=pd.read_csv("/content/Salary_dataset.csv")

In [ ]:
df.head()

Unnamed: 0  YearsExperience   Salary
0           0              1.2  39344.0
1           1              1.4  46206.0
2           2              1.6  37732.0
3           3              2.1  43526.0
4           4              2.3  39892.0

In [ ]:
df.tail()

Unnamed: 0  YearsExperience    Salary
25          25              9.1  105583.0
26          26              9.6  116970.0
27          27              9.7  112636.0
28          28             10.4  122392.0
29          29             10.6  121873.0

In [ ]:
x=df.YearsExperience
y=df.Salary

In [ ]:
x=df['YearsExperience'].values
y=df['Salary'].values

In [ ]:
x

array([ 1.2,  1.4,  1.6,  2.1,  2.3,  3. ,  3.1,  3.3,  3.3,  3.8,  4. ,
        4.1,  4.1,  4.2,  4.6,  5. ,  5.2,  5.4,  6. ,  6.1,  6.9,  7.2,
        8. ,  8.3,  8.8,  9.1,  9.6,  9.7, 10.4, 10.6])

In [ ]:
x=df.iloc[:,1].values

In [ ]:
x

array([ 1.2,  1.4,  1.6,  2.1,  2.3,  3. ,  3.1,  3.3,  3.3,  3.8,  4. ,
        4.1,  4.1,  4.2,  4.6,  5. ,  5.2,  5.4,  6. ,  6.1,  6.9,  7.2,
        8. ,  8.3,  8.8,  9.1,  9.6,  9.7, 10.4, 10.6])

In [ ]:
y=df.iloc[:,-1].values
y

array([ 39344.,  46206.,  37732.,  43526.,  39892.,  56643.,  60151.,
        54446.,  64446.,  57190.,  63219.,  55795.,  56958.,  57082.,
        61112.,  67939.,  66030.,  83089.,  81364.,  93941.,  91739.,
        98274., 101303., 113813., 109432., 105583., 116970., 112636.,
       122392., 121873.])

In [ ]:
import numpy as np
x=np.array(x)
y=np.array(y)
d_array=df['YearsExperience'].to_numpy().reshape(-1,1)
d_array

array([[ 1.2],
       [ 1.4],
       [ 1.6],
       [ 2.1],
       [ 2.3],
       [ 3. ],
       [ 3.1],
       [ 3.3],
       [ 3.3],
       [ 3.8],
       [ 4. ],
       [ 4.1],
       [ 4.1],
       [ 4.2],
       [ 4.6],
       [ 5. ],
       [ 5.2],
       [ 5.4],
       [ 6. ],
       [ 6.1],
       [ 6.9],
       [ 7.2],
       [ 8. ],
       [ 8.3],
       [ 8.8],
       [ 9.1],
       [ 9.6],
       [ 9.7],
       [10.4],
       [10.6]])

In [ ]:
x=x.reshape(-1,1)
x
y=y.reshape(1,-1)
y

array([[ 39344.,  46206.,  37732.,  43526.,  39892.,  56643.,  60151.,
         54446.,  64446.,  57190.,  63219.,  55795.,  56958.,  57082.,
         61112.,  67939.,  66030.,  83089.,  81364.,  93941.,  91739.,
         98274., 101303., 113813., 109432., 105583., 116970., 112636.,
        122392., 121873.]])

In [ ]:
x_mean=x.mean()
x_std=x.std()
x_standardized=(x-x_mean)/x_std
x_standardized

array([[-1.51005294],
       [-1.43837321],
       [-1.36669348],
       [-1.18749416],
       [-1.11581443],
       [-0.86493538],
       [-0.82909552],
       [-0.75741579],
       [-0.75741579],
       [-0.57821647],
       [-0.50653674],
       [-0.47069688],
       [-0.47069688],
       [-0.43485702],
       [-0.29149756],
       [-0.1481381 ],
       [-0.07645838],
       [-0.00477865],
       [ 0.21026054],
       [ 0.2461004 ],
       [ 0.53281931],
       [ 0.6403389 ],
       [ 0.92705781],
       [ 1.03457741],
       [ 1.21377673],
       [ 1.32129632],
       [ 1.50049564],
       [ 1.5363355 ],
       [ 1.78721455],
       [ 1.85889428]])

In [ ]:
x_min=x.min()
x_max=x.max()
x_norm=(x-x_min)/(x_max-x_min)
x_norm

array([[0.        ],
       [0.0212766 ],
       [0.04255319],
       [0.09574468],
       [0.11702128],
       [0.19148936],
       [0.20212766],
       [0.22340426],
       [0.22340426],
       [0.27659574],
       [0.29787234],
       [0.30851064],
       [0.30851064],
       [0.31914894],
       [0.36170213],
       [0.40425532],
       [0.42553191],
       [0.44680851],
       [0.5106383 ],
       [0.5212766 ],
       [0.60638298],
       [0.63829787],
       [0.72340426],
       [0.75531915],
       [0.80851064],
       [0.84042553],
       [0.89361702],
       [0.90425532],
       [0.9787234 ],
       [1.        ]])

In [ ]:
m=np.random.randn()
c=np.random.randn()
print("randomly initiallized m",m)
print("randomly intialized  interceptc",c)

randomly initiallized m -0.881321464834114
randomly intialized  interceptc -1.334461116807939


In [ ]:
def predict(x,m,c):
   y_pred=m*x+c
   return y_pred

In [ ]:
#make predictions using initial values
y_pred=predict(x_norm,m,c)
y_pred

array([[-1.33446112],
       [-1.35321264],
       [-1.37196416],
       [-1.41884296],
       [-1.43759448],
       [-1.5032248 ],
       [-1.51260056],
       [-1.53135208],
       [-1.53135208],
       [-1.57823088],
       [-1.5969824 ],
       [-1.60635816],
       [-1.60635816],
       [-1.61573392],
       [-1.65323697],
       [-1.69074001],
       [-1.70949153],
       [-1.72824305],
       [-1.78449761],
       [-1.79387337],
       [-1.86887945],
       [-1.89700673],
       [-1.97201281],
       [-2.0001401 ],
       [-2.0470189 ],
       [-2.07514618],
       [-2.12202498],
       [-2.13140074],
       [-2.19703106],
       [-2.21578258]])

In [ ]:
#display first 5 predictions
y_pred[:5]

array([[-1.33446112],
       [-1.35321264],
       [-1.37196416],
       [-1.41884296],
       [-1.43759448]])

In [ ]:
def compute_cost(y,y_pred):
  m=len(y)
  cost=(1/(2*m))*np.sum(y-pred_y)**2
  return cost

In [ ]:
learning_rate=0.01
epochs=1000
print("lr",learning_rate)
print("epochs",epochs)

lr 0.01
epochs 1000


In [ ]:
def predict_salary(years_experience,m,c,x_min,x_max):
  x=np.array(years_experience).reshape(-1,1)
  x_norm=(x-x_min)/(x_max-x_min)
  salary_pred=m*x_norm+c
  return salary_pred
print(predict_salary(-5,m,c,x_min,x_max))

[[-0.75316398]]
